sgpa/sgpa/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sgpa/', include('sgpa2016.urls',namespace="sgpa2016")),
    
    url(r'^$', 'sgpa2016.views.inicio'),
    url(r'^ingresar/$','sgpa2016.views.ingresar'),
    url(r'^index/$','sgpa2016.views.index'),
    url(r'^cerrar/$', 'sgpa2016.views.cerrar'),
    url(r'^creditos/$', 'sgpa2016.views.creditos'),
]

sgpa/sgpa2016/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^usuarios/registro/$', views.registrar_usuarios, name='registrar_usuarios'),
    url(r'^usuarios/index/$', views.index_usuarios, name='index_usuarios'),
    url(r'^usuarios/modificar_contrasena/$', views.modificar_contrasena, name='modificar_contrasena'),
    url(r'^usuarios/(?P<user_id>\d+)/editar/$', views.editar_usuarios, name='editar_usuarios'),
    url(r'^usuarios/(?P<user_id>\d+)/eliminar/$', views.eliminar_usuarios, name='eliminar_usuarios'),
    url(r'^usuarios/(?P<user_id>\d+)/delete/$', views.delete_usuarios, name='delete_usuarios'),
    url(r'^usuarios/(?P<user_id>\d+)/ver/$', views.ver_usuarios, name='ver_usuarios'),
    url(r'^usuarios/(?P<user_id>\d+)/asignar/$', views.asignar_roles_usuarios_proyecto, name='asignar_roles_usuarios_proyecto'),
    url(r'^roles/crear/$', views.crear_roles, name='crear_roles'),
    url(r'^roles/index/$', views.index_roles, name='index_roles'),
    url(r'^roles/(?P<rol_id>\d+)/editar/$', views.editar_roles, name='editar_roles'),
    url(r'^roles/(?P<rol_id>\d+)/ver/$', views.ver_roles, name='ver_roles'),
    url(r'^roles/(?P<rol_id>\d+)/eliminar/$', views.eliminar_roles, name='eliminar_roles'),
    url(r'^roles/(?P<rol_id>\d+)/delete/$', views.delete_roles, name='delete_roles'),
    url(r'^proyectos/crear/$', views.crear_proyectos, name='crear_proyectos'),
    url(r'^proyectos/index/$', views.index_proyectos, name='index_proyectos'),
    url(r'^proyectos/(?P<proyecto_id>\d+)/definir/$', views.definir_proyectos, name='definir_proyectos'),
    url(r'^proyectos/(?P<proyecto_id>\d+)/editar/$', views.editar_proyectos, name='editar_proyectos'),
    url(r'^proyectos/(?P<proyecto_id>\d+)/ver/$', views.ver_proyectos, name='ver_proyectos'),
]

sgpa/sgpa2016/models.py
"""
Modelos
"""
# -*- encoding: utf-8 -*-
from django.db import models
from django.conf import settings
from django.utils import timezone

"""
Clase Permisos.
"""
class Permisos(models.Model):
    nombre = models.CharField(max_length=50, default="")
    nivel = models.IntegerField()
    estado = models.BooleanField(default=False)
    def __unicode__(self):
        return u"%s" % self.nombre

    def __str__(self):
        return self.nombre

"""
Clase Roles.
"""
class Roles(models.Model):
    nombre = models.CharField(max_length=25, default="")
    tipo = models.BooleanField(default=False) #True: Roles de Sistema. False: Roles de Usuario.
    estado = models.BooleanField(default=False)
    observacion = models.CharField(max_length=50, default="")
    permisos = models.ManyToManyField(Permisos, through='Permisos_Roles')
    
    def __unicode__(self):
        return u"%s" % self.nombre
    
    def __str__(self):
        return self.nombre
"""
Clase Usuarios.
"""
class Usuarios(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    telefono = models.CharField(max_length=15, default="")
    direccion = models.CharField(max_length=45, default="")
    tipo = models.CharField(max_length=10, default="")
    observacion = models.CharField(max_length=50, default="")
    roles = models.ManyToManyField(Roles, through='Roles_Usuarios')
    
    def __str__(self):
        return self.user.username

class Permisos_Roles(models.Model):
    permisos = models.ForeignKey(Permisos)
    roles = models.ForeignKey(Roles)
    
class Roles_Usuarios(models.Model):
    roles = models.ForeignKey(Roles)
    usuario = models.ForeignKey(Usuarios)

"""
Clase Proyectos.
"""
class Proyectos(models.Model):
    nombre_largo = models.CharField(max_length=25, default="")
    nombre_corto = models.CharField(max_length=10, default="")
    tipo = models.BooleanField(default=True) #True: Proyecto. False: Servicio.
    descripcion = models.CharField(max_length=50, default="")
    fecha_inicio = models.DateField(default=timezone.now)
    fecha_fin_estimado = models.DateField(default=timezone.now)
    fecha_fin_real = models.DateField(default=timezone.now)
    observaciones = models.CharField(max_length=50, default="")
    estado = models.IntegerField(default=1) #1: Pendiente. 2: Anulado. 3: Activo. 4: Finalizado.
    usuarios = models.ManyToManyField(Usuarios, through='Usuarios_Proyectos')
    
    def __str__(self):
        return self.nombre_largo
    
class Usuarios_Proyectos(models.Model):
    proyecto = models.ForeignKey(Proyectos)
    usuarios = models.ForeignKey(Usuarios)

sgpa/sgpa2016/views.py
# -*- encoding: utf-8 -*-

from django.shortcuts import get_object_or_404, render, render_to_response
from django.contrib.auth.models import User

from .forms import RegistroUserForm, EditarUserForm, BuscarUserForm, CrearRolForm, BuscarRolForm, EditarRolForm, ModificarContrasenaForm, AsignarRolForm, CrearProyectoForm, DefinirProyectoForm, BuscarProyectoForm, EditarProyectoForm, ElegirProyectoForm
from .models import Usuarios, Permisos, Roles, Permisos_Roles, Roles_Usuarios, Proyectos, Usuarios_Proyectos

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm

from django.http import HttpResponseRedirect
from django.template import RequestContext
from datetime import datetime
from django.contrib.auth.hashers import make_password

"""Ingreso al sistema."""
def inicio(request):    
    if request.user.is_anonymous():
        return HttpResponseRedirect('/ingresar')
    else:
        return HttpResponseRedirect('/index')

def ingresar(request):
    now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    request.session['last_activity'] = str(now)
    
    if not request.user.is_anonymous():
        return HttpResponseRedirect('/index')
    if request.method == 'POST':
        formulario = AuthenticationForm(request.POST)
        if formulario.is_valid:
            usuario = request.POST['username']
            clave = request.POST['password']
            acceso = authenticate(username=usuario, password=clave)
            if acceso is not None:
                if acceso.is_active:
                    login(request, acceso)

                    return HttpResponseRedirect('/index')
                else:
                    return render_to_response('noactivo.html', context_instance=RequestContext(request))
            else:
                return render_to_response('nousuario.html', context_instance=RequestContext(request))
    else:
        formulario = AuthenticationForm()
    return render_to_response('login.html',{'formulario':formulario}, context_instance=RequestContext(request))

@login_required(login_url='/ingresar')
def cerrar(request):
    logout(request)
    return HttpResponseRedirect('/ingresar')

@login_required(login_url='/ingresar')
def index(request):
    comprobar(request)
        
    usuario = request.user
    us = Usuarios.objects.get(id=usuario.id)
    permiso = Permisos.objects.filter(nombre="Ver Página de Administración")
    rol = Roles.objects.filter(permisos=permiso)
    ru = Usuarios.objects.get(roles=rol)
    saludo = saludo_dia()
        
    if us == ru:
        return render_to_response('inicio_admin.html', {'usuario':usuario, 'saludo':saludo}, context_instance=RequestContext(request))    
    else:
        proyectos = Proyectos.objects.filter(usuarios__id=usuario.id)
        
    if not proyectos:
        return render_to_response('noasignado.html', {'usuario':usuario, 'saludo':saludo}, context_instance=RequestContext(request))
    else:
        if request.method == 'POST':
            form = ElegirProyectoForm(request.POST, request.FILES)
            if form.is_valid():
                cleaned_data = form.cleaned_data
                proyecto_id = cleaned_data.get('proyecto_id')
                proyecto = get_object_or_404(Proyectos,id=proyecto_id)
                   
                return render_to_response('inicio_usuario.html', {'usuario':usuario, 'proyecto':proyecto, 'saludo':saludo}, context_instance=RequestContext(request))   
        else:
            form = ElegirProyectoForm()
            
        return render(request, 'elegir_proyecto.html', {'usuario':usuario, 'proyectos':proyectos, 'saludo':saludo, 'form': form})   
    
def creditos(request):
    comprobar(request)        
    usuario = request.user
    saludo = saludo_dia()
    
    staff=verificar_permiso(usuario, "Ver Index de Admin")
   
    return render_to_response('creditos.html', {'usuario':usuario, 'saludo':saludo, 'staff':staff}, context_instance=RequestContext(request))    
     
"""Administración de Usuarios"""
@login_required(login_url='/ingresar')
def registrar_usuarios(request):
    usuario = request.user
    accion = "Registro de Usuarios"
    
    staff = verificar_permiso(usuario, accion)
    
    if staff:
        aid = 1
        comprobar(request)
        saludo = saludo_dia()
            
        if request.method == 'POST':
            form = RegistroUserForm(request.POST, request.FILES)
        
            if form.is_valid():
                cleaned_data = form.cleaned_data
                username = cleaned_data.get('username')
                password = cleaned_data.get('password')
                email = cleaned_data.get('email')
                first_name = cleaned_data.get('first_name')
                last_name = cleaned_data.get('last_name')
                telefono = cleaned_data.get('telefono')
                direccion = cleaned_data.get('direccion')
                tipo = cleaned_data.get('tipo')
                observacion = cleaned_data.get('observacion')
        
                user_model = User.objects.create_user(username=username, password=password)
                user_model.email = email
                user_model.first_name = first_name
                user_model.last_name = last_name
                user_model.is_active = True
                user_model.save()
                    
                user_profile = Usuarios()
                user_profile.user = user_model
                user_profile.id = user_model.id
                user_profile.telefono = telefono
                user_profile.direccion = direccion
                user_profile.tipo = tipo
                user_profile.observacion = observacion
                
                user_profile.save()
                return render_to_response('usuarios/gracias.html', {'usuario':usuario, 'saludo':saludo, 'um':user_model, 'up':user_profile, 'aid':aid}, context_instance=RequestContext(request))   
        else:
            form = RegistroUserForm()
        
        return render(request, 'usuarios/registro.html', {'usuario':usuario, 'saludo':saludo, 'form': form})
    else:
        return HttpResponseRedirect('/index')
    
@login_required(login_url='/ingresar')
def index_usuarios(request):
    usuario = request.user
    accion = "Index de Usuarios"
    
    staff = verificar_permiso(usuario, accion)
    
    if staff:      
        comprobar(request)
       
        saludo = saludo_dia()
        
        users = User.objects.filter(is_active=True).order_by('id')
        
        filas= users.count() - 1
        
        if request.method == 'POST':
            results = User.objects.filter(is_active=True)
            form = BuscarUserForm(request.POST)
            
            if form.is_valid():
                uid = request.POST.get('id', None)
                if uid:
                    if uid != usuario.id:
                        results = results.filter(id__iexact=uid)
                    else:
                        results = None
                        
                uusername = request.POST.get('username', None)
                if uusername:
                    if uusername != usuario.username:
                        results = results.filter(username__contains=uusername)
                    else:
                        results = None
                        
                uemail = request.POST.get('email', None)
                if uemail:
                    if uemail != usuario.email:
                        results = results.filter(email__contains=uemail)
                    else:
                        results = None
                        
                first_name = request.POST.get('first_name', None)
                if first_name:
                    if first_name != usuario.first_name:
                        results = results.filter(first_name__contains=first_name)
                    else:
                        results = None
                        
                last_name = request.POST.get('last_name', None)
                if last_name:
                    if last_name != usuario.last_name:
                        results = results.filter(last_name__contains=last_name)
                    else:
                        results = None
                                 
                if not uid and not uusername and not uemail and not first_name and not last_name:
                    results = None
                
                if results:
                    results.order_by('id')
                return render_to_response('usuarios/results.html', {'usuario':usuario, 'saludo':saludo, 'results':results}, context_instance=RequestContext(request))
        else:
            form = BuscarUserForm()
        
        return render(request, 'usuarios/index.html', {'usuario':usuario, 'saludo':saludo, 'users':users, 'filas':filas})
    else:
        return HttpResponseRedirect('/index')
        
@login_required(login_url='/ingresar')
def editar_usuarios(request, user_id):
    usuario = request.user
    accion = "Editar Usuarios"
    
    staff = verificar_permiso(usuario, accion)
    
    if staff:
        aid = 2
        comprobar(request)
        
        usuario = request.user
        saludo = saludo_dia()
        
        user_model = get_object_or_404(User, pk=user_id)
        user_profile = get_object_or_404(Usuarios, id=user_id)
    
        if request.method == 'POST':
            form = EditarUserForm(request.POST, request.FILES)
            if form.is_valid():
                password = form.cleaned_data['password']
                if password:
                    user_model.password =  make_password(password)
                user_model.email = form.cleaned_data['email']
                user_model.first_name = form.cleaned_data['first_name']
                user_model.last_name = form.cleaned_data['last_name']  

sgpa/sgpa2016/templates/usuarios/index.html
{% extends 'base.html' %}
{% block title %}Index Usuarios{% endblock title %}
{% block content %}
	<link href="/static/style1.css" rel="stylesheet" type="text/css" />
		<div id="welcome" align="center">	
			{{saludo}}, <a href="{% url 'sgpa2016:modificar_contrasena' %}">{{usuario.username}}</a>!
		</div>
		
	<link href="/static/menu.css" rel="stylesheet" type="text/css" />
		<nav>
			<ul id='nav'>
		  		<li><a href='/'>Inicio</a></li>
		  		<li><a href='/sgpa/usuarios/index/'>Usuarios</a></li>
		  		<li><a href='/sgpa/roles/index/'>Roles</a></li>
		  		<li><a href='/sgpa/proyectos/index/'>Proyectos</a></li>
		  		<li><a href='/cerrar'>Cerrar</a></li>
    		</ul>
		</nav>
		
		<script language="javascript">
			function nuevo_usuario() {
				location.href="{% url 'sgpa2016:registrar_usuarios' %}";
			}
			
			function limpiar() {
				document.getElementById("form_busqueda").reset();
			}
			
			var cursor;
			if (document.all) {
				// Está utilizando EXPLORER
				cursor='hand';
			} else {
				// Está utilizando MOZILLA/NETSCAPE
				cursor='pointer';
			}
		</script>
		
		<link href="/static/estilos.css" rel="stylesheet" type="text/css" />
		<div id="pagina">
			<div id="zonaContenidoPP">
				<div align="center">
				
				<div id="tituloForm" class="header">BUSCAR USUARIO </div>
				<div id="frmBusqueda">
				<form id="form_busqueda" name="form_busqueda" method="post" action="">
					{% csrf_token %}
					<table class="fuente8" width="98%" cellspacing=0 cellpadding=3 border=0>
					{{ form.errors }}				
						<tr>
							<td width="16%">ID de Usuario </td>
							<td width="68%"><input id="id" type="text" class="cajaPequena" NAME="id" maxlength="10" value=""></td>
							<td width="5%">&nbsp;</td>
							<td width="5%">&nbsp;</td>
							<td width="6%" align="right"></td>
						</tr>
						<tr>
							<td>Nombre de Usuario</td>
							<td><input id="username" name="username" type="text" class="cajaGrande" maxlength="45" value=""></td>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td>Email</td>
							<td><input id="email" name="email" type="text" class="cajaGrande" maxlength="45" value=""></td>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td>Nombres</td>
							<td><input id="first_name" name="first_name" type="text" class="cajaGrande" maxlength="45" value=""></td>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td>Apellidos</td>
							<td><input id="last_name" name="last_name" type="text" class="cajaGrande" maxlength="45" value=""></td>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
						</tr>
						
					</table>
					
					</div>
					<div id="botonBusqueda">
						<td style="text-align:right"><button class="button" type="submit">BUSCAR</button></td>
        				<td style="text-align:right"><a onClick="limpiar()" onMouseOver="style.cursor=cursor" class="button">LIMPIAR</a></td>
        				<td style="text-align:left"><a onClick="nuevo_usuario()" onMouseOver="style.cursor=cursor" class="button" >NUEVO USUARIO</a></td>
					</div>
				</form>
					
			<div id="lineaResultado">
			  <table class="fuente8" width="80%" cellspacing=0 cellpadding=3 border=0>
			  	<tr>
				<td width="50%" align="left">Nro. de Usuarios encontrados. <input id=filas type="text" class="cajaPequena" NAME=filas maxlength="5" value="{{filas}}"></td>
			  </table>
			</div>
			
			<td>&nbsp;</td>
			<td>&nbsp;</td>
					<div id="cabeceraResultado" class="header">
						LISTA DE USUARIOS </div>
						<div id="frmResultado">
							<table class="fuente8" width="100%" cellspacing=0 cellpadding=3 border=0 ID="Table1">
								<tr class="cabeceraTabla">
									<td width="7%">ÍTEM</td>
									<td width="8%">ID</td>
									<td width="15%">NOMBRE DE USUARIO</td>
									<td width="15%">NOMBRES </td>
									<td width="15%">APELLIDOS </td>
									<td width="20%">EMAIL</td>
									<td width="5%">Assign</td>
									<td width="5%">Read</td>
									<td width="5%">Update</td>
									<td width="5%">Delete</td>
									<td width="10%">&nbsp;</td>
								</tr>
							</table>
							<div class="ScrollStyle">
							<table class="fuente8" width="100%" cellspacing=0 cellpadding=3 border=0 ID="Table1">
								{% if users and filas > 0 %}
									{% for user in users %}
										{% if user.is_active == True %}
											{% if user.id != usuario.id %}
												{% if forloop.counter|divisibleby:2  %}
													<tr class="itemImparTabla">
														<td class="aCentro" width="7%"><div align="center">{{forloop.counter0}}</div></td>
														<td width="8%"><div align="center">{{user.id}}</div></td>
														<td width="15%"><div align="center">{{user.username}}</div></td>
														<td width="15%"><div align="center">{{user.first_name}}</div></td>
														<td width="15%"><div align="center">{{user.last_name}}</div></td>
														<td width="20%"><div align="center">{{user.email}}</div></td>
														<td width="5%"><div align="center"><a href="{% url 'sgpa2016:asignar_roles_usuarios_proyecto' user.id %}"><img src="/static/img/list.png" width="16" height="16" border="0" title="Agregar Roles/Permisos"></a></div></td>
														<td width="5%"><div align="center"><a href="{% url 'sgpa2016:ver_usuarios' user.id %}"><img src="/static/img/ver.png" width="16" height="16" border="0" title="Visualizar"></a></div></td>
														<td width="5%"><div align="center"><a href="{% url 'sgpa2016:editar_usuarios' user.id %}"><img src="/static/img/modificar.png" width="16" height="16" border="0" title="Modificar"></a></div></td>
														<td width="5%"><div align="center"><a href="{% url 'sgpa2016:eliminar_usuarios' user.id %}"><img src="/static/img/eliminar.png" width="16" height="16" border="0" title="Eliminar"></a></div></td>
													</tr>
												{% else %}
													<tr class="itemParTabla"> 
														<td class="aCentro" width="7%"><div align="center">{{forloop.counter0}}</div></td>
														<td width="8%"><div align="center">{{user.id}}</div></td>
														<td width="15%"><div align="center">{{user.username}}</div></td>
														<td width="15%"><div align="center">{{user.first_name}}</div></td>
														<td width="15%"><div align="center">{{user.last_name}}</div></td>
														<td width="20%"><div align="center">{{user.email}}</div></td>
														<td width="5%"><div align="center"><a href="{% url 'sgpa2016:asignar_roles_usuarios_proyecto' user.id %}"><img src="/static/img/list.png" width="16" height="16" border="0" title="Agregar Roles/Permisos"></a></div></td>
														<td width="5%"><div align="center"><a href="{% url 'sgpa2016:ver_usuarios' user.id %}"><img src="/static/img/ver.png" width="16" height="16" border="0" title="Visualizar"></a></div></td>
														<td width="5%"><div align="center"><a href="{% url 'sgpa2016:editar_usuarios' user.id %}"><img src="/static/img/modificar.png" width="16" height="16" border="0" title="Modificar"></a></div></td>
														<td width="5%"><div align="center"><a href="{% url 'sgpa2016:eliminar_usuarios' user.id %}"><img src="/static/img/eliminar.png" width="16" height="16" border="0" title="Eliminar"></a></div></td>
													</tr>
												{% endif %}
											{% endif %}
										{% endif %}
									{% endfor %}
								{% else %}
									<p>No hay usuarios registrados en la base de datos.</p>
								{% endif %}
								
							</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>								
		
{% endblock content %}

sgpa/sgpa2016/templates/usuarios/results.html
{% extends 'base.html' %}
{% block title %}Buscar Usuarios{% endblock title %}
{% block content %}
	<link href="/static/style1.css" rel="stylesheet" type="text/css" />
		<div id="welcome" align="center">	
			{{saludo}}, <a href="{% url 'sgpa2016:modificar_contrasena' %}">{{usuario.username}}</a>!
		</div>
		
	<link href="/static/menu.css" rel="stylesheet" type="text/css" />
		<nav>
			<ul id='nav'>
		  		<li><a href='/'>Inicio</a></li>
		  		<li><a href='/sgpa/usuarios/index/'>Usuarios</a></li>
		  		<li><a href='/sgpa/roles/index/'>Roles</a></li>
		  		<li><a href='/sgpa/proyectos/index/'>Proyectos</a></li>
		  		<li><a href='/cerrar'>Cerrar</a></li>
    		</ul>
		</nav>
		
		<link href="/static/estilos.css" rel="stylesheet" type="text/css" />
		<div id="pagina">
			<div id="zonaContenidoPP">
				<div align="center">
				
					<div id="cabeceraResultado" class="header">
						USUARIOS ENCONTRADOS </div>
						<div id="frmResultado">
							<table class="fuente8" width="100%" cellspacing=0 cellpadding=3 border=0 ID="Table1">
								<tr class="cabeceraTabla">
									<td width="7%">ÍTEM</td>
									<td width="8%">ID</td>
									<td width="15%">NOMBRE DE USUARIO</td>
									<td width="15%">NOMBRES </td>
									<td width="15%">APELLIDOS </td>
									<td width="20%">EMAIL</td>
									<td width="5%">Assign</td>
									<td width="5%">Read</td>
									<td width="5%">Update</td>
									<td width="5%">Delete</td>
									<td width="10%">&nbsp;</td>
								</tr>
							</table>
							<div class="ScrollStyle">
							<table class="fuente8" width="100%" cellspacing=0 cellpadding=3 border=0 ID="Table1">
								{% if results %}
									{% for user in results %}
										{% if user.is_active == True %}
											{% if user.id != usuario.id %}
												{% if forloop.counter|divisibleby:2  %}
													<tr class="itemImparTabla">
														<td class="aCentro" width="7%"><div align="center">{{forloop.counter0}}</div></td>
														<td width="8%"><div align="center">{{user.id}}</div></td>
														<td width="15%"><div align="center">{{user.username}}</div></td>
														<td width="15%"><div align="center">{{user.first_name}}</div></td>
														<td width="15%"><div align="center">{{user.last_name}}</div></td>
														<td width="20%"><div align="center">{{user.email}}</div></td>
														<td width="5%"><div align="center"><a href="#"><img src="/static/img/list.png" width="16" height="16" border="0" title="Agregar Roles/Permisos"></a></div></td>
														<td width="5%"><div align="center"><a href="{% url 'sgpa2016:ver_usuarios' user.id %}"><img src="/static/img/ver.png" width="16" height="16" border="0" title="Visualizar"></a></div></td>
														<td width="5%"><div align="center"><a href="{% url 'sgpa2016:editar_usuarios' user.id %}"><img src="/static/img/modificar.png" width="16" height="16" border="0" title="Modificar"></a></div></td>
														<td width="5%"><div align="center"><a href="{% url 'sgpa2016:eliminar_usuarios' user.id %}"><img src="/static/img/eliminar.png" width="16" height="16" border="0" title="Eliminar"></a></div></td>
													</tr>
												{% else %}
													<tr class="itemParTabla"> 
														<td class="aCentro" width="7%"><div align="center">{{forloop.counter0}}</div></td>
														<td width="8%"><div align="center">{{user.id}}</div></td>
														<td width="15%"><div align="center">{{user.username}}</div></td>
														<td width="15%"><div align="center">{{user.first_name}}</div></td>
														<td width="15%"><div align="center">{{user.last_name}}</div></td>
														<td width="20%"><div align="center">{{user.email}}</div></td>
														<td width="5%"><div align="center"><a href="#"><img src="/static/img/list.png" width="16" height="16" border="0" title="Agregar Roles/Permisos"></a></div></td>
														<td width="5%"><div align="center"><a href="{% url 'sgpa2016:ver_usuarios' user.id %}"><img src="/static/img/ver.png" width="16" height="16" border="0" title="Visualizar"></a></div></td>
														<td width="5%"><div align="center"><a href="{% url 'sgpa2016:editar_usuarios' user.id %}"><img src="/static/img/modificar.png" width="16" height="16" border="0" title="Modificar"></a></div></td>
														<td width="5%"><div align="center"><a href="{% url 'sgpa2016:eliminar_usuarios' user.id %}"><img src="/static/img/eliminar.png" width="16" height="16" border="0" title="Eliminar"></a></div></td>
													</tr>
												{% endif %}
											{% endif %}
										{% endif %}
									{% endfor %}
								{% else %}
									<p>No hay usuarios registrados en la base de datos.</p>
								{% endif %}
								
							</table>
							</div>
							<div id="botonBusqueda">
        							<a class="button" onClick="javascript:history.go(-1);"> ATRÁS</a>
        					</div>
						</div>
					</div>
				</div>
			</div>
		</div>								
		
{% endblock content %}